export const Images = {
  AppLogo: require('./appLogo.png'),
  SplashImage: require('./splashImage.jpg'),
  English: require('./englsih.png'), // Note: Typo in filename 'Englsih.png'
  Gujarati: require('./gujarati.png'),
  Hindi: require('./hindi.png'),
  Marathi: require('./marathi.png'),
  Odia: require('./odia.png'),
  Punjabi: require('./punjabi.png'),
  Telugu: require('./telugu.png'),
  LanguageHeader: require('./languageHeader.png'),
  Loading: require('./LoaderMain.gif'),
  Weather: require('./weather.png'),
  SplashVideo: require('./splash.mp4'),
  Check: require('./check.gif'),
  IndianFlag: require('./indianFlag.png'),
  BottomBGNew: require('./BottomTabBg_M.png'),
  Loading2: require('./Loading2.gif'),
  SplashGif: require('./splashNew.gif'),
  GrBg: require('./grBG.png'),
  AccuweatherLogo: require('./accuweatherLogo.png'),
  WeatherPlaceholder: require('./weatherPlaceholder.png'),
  KisaniAvatar: require('./kisaniAvatar.png'),
  CropIcon: require('./wheat.png'),
  landIcon: require('./land.png'),
  placeHolder: require('./placeholder.jpg'),
  geoTag: require('./geoTag.png'),
  land1: require('./1.png'),
  land2: require('./2.png'),
  land3: require('./3.png'),
  noWeatherData: require('./noWeatherData.png'),
  plusIcon: require('./plus.png')

};
