import { ImageSourcePropType } from 'react-native';

export const weatherIconMap: { [key: string]: ImageSourcePropType } = {
  'sunny': require('../assets/images/weatherIcons/Sunny.png'),
  'partly sunny': require('../assets/images/weatherIcons/Partly sunny.png'),
  'partly cloudy': require('../assets/images/weatherIcons/Partly cloudy.png'),
  'mostly sunny': require('../assets/images/weatherIcons/Mostly sunny.png'),
  'mostly cloudy': require('../assets/images/weatherIcons/Mostly cloudy.png'),
  'cloudy': require('../assets/images/weatherIcons/Cloudy.png'),
  'showers': require('../assets/images/weatherIcons/Showers.png'),
  't-storms': require('../assets/images/weatherIcons/T-storms.png'),
  'rain': require('../assets/images/weatherIcons/Rain.png'),
  'snow': require('../assets/images/weatherIcons/Snow.png'),
  'sleet': require('../assets/images/weatherIcons/Sleet.png'),
  'windy': require('../assets/images/weatherIcons/Windy.png'),
  'fog': require('../assets/images/weatherIcons/Fog.png'),
  'hazy sunshine': require('../assets/images/weatherIcons/Hazy sunshine.png'),
  'hazy moonlight': require('../assets/images/weatherIcons/Hazy moonlight.png'),
  'clear': require('../assets/images/weatherIcons/Clear.png'),
  'cold': require('../assets/images/weatherIcons/Cold.png'),
  'hot': require('../assets/images/weatherIcons/Hot.png'),
  'dreary (overcast)': require('../assets/images/weatherIcons/Dreary (overcast).png'),
  'flurries': require('../assets/images/weatherIcons/Flurries.png'),
  'freezing rain': require('../assets/images/weatherIcons/Freezing rain.png'),
  'ice': require('../assets/images/weatherIcons/Ice.png'),
  'intermittent clouds': require('../assets/images/weatherIcons/Intermittent clouds.png'),
  'mostly clear': require('../assets/images/weatherIcons/Mostly clear.png'),
  'mostly cloudy w: flurries': require('../assets/images/weatherIcons/Mostly cloudy w: flurries.png'),
  'mostly cloudy w: showers': require('../assets/images/weatherIcons/Mostly cloudy w: showers.png'),
  'mostly cloudy w: snow': require('../assets/images/weatherIcons/Mostly cloudy w: snow.png'),
  'mostly cloudy w: t-storms': require('../assets/images/weatherIcons/Mostly cloudy w: T-storms.png'),
  'partly cloudy w: showers': require('../assets/images/weatherIcons/Partly cloudy w: showers.png'),
  'partly cloudy w: t-storms': require('../assets/images/weatherIcons/Partly cloudy w: T-storms.png'),
  'partly sunny w: flurries': require('../assets/images/weatherIcons/Partly sunny w: flurries.png'),
  'partly sunny w: showers': require('../assets/images/weatherIcons/Partly sunny w: showers.png'),
  'partly sunny w: t-storms': require('../assets/images/weatherIcons/Partly sunny w: T-storms.png'),
  'rain and snow': require('../assets/images/weatherIcons/Rain and snow.png'),
};